builds:
  - main: ./cmd/pbcopy
    binary: pbcopy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
checksum:
  name_template: 'pbcopy-checksums.txt'
archives:
  - name_template: "pbcopy-{{ .Os }}-{{ .Arch }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
